[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7.0"
actix-files = "0.6.6"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
chrono = "0.4"